apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
      - name: edge-service
        image: edge-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        env:
          - name: BPL_JVM_THREAD_COUNT
            value: "50"
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-service:8888
          - name: CATALOG_SERVICE_URL
            value: http://catalog-service:9001
          - name: ORDER_SERVICE_URL
            value: http://order_service:9002
          - name: SPRING_REDIS_HOST
            value: polar-redis
